on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to Sparked Host
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with Password
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Send Restart Power Action
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: 'https://control.sparkedhost.us'
          server-id: ${{ secrets.APOLLO_SERVER_ID }}
          bearer-token: ${{ secrets.APOLLO_API_KEY }}
          power-action: 'restart'
